#!/usr/bin/env python3
"""Insert outreach drafts generated by a Claude Code workflow session
(.claude/workflows/generate-outreach-emails.js, scale-generate.js) as
pending drafts.

Usage: python3 scripts/piq_write_drafts.py <drafts.json>

drafts.json is a JSON array of objects with (at minimum): company_id,
contact_id, sequence_step, subject, body, personalization_notes.

This is the single writer both workflows should invoke — previously
scale-generate.js called an equivalent script that lived only at
/Users/avanish/prospectIQ/.pipeline-queues/piq_write_drafts.py, untracked
in any repository, while generate-outreach-emails.js asked a sub-agent to
write equivalent insert code from a prose field list on every run. Two
real defects followed from that split:

1. The prose-driven path's field list never mentioned `model`, so every
   draft it wrote had model=NULL and was silently dropped from the send
   schedule by send_scheduler.py's `if d.get("model")` filter — the exact
   failure mode that filter's own comment says already caused one "silent
   send blackout" before. Routing both workflows through this one script
   makes that impossible: `model` is set in code, not left to an agent's
   discretion each run.
2. The untracked script bypassed Database.insert_outreach_draft()'s
   dedup guards (same company/contact/step, and cross-company email dedup
   for step 1) by inserting directly via .table().insert(). Fixed here by
   routing through insert_outreach_draft() instead.

Also applies the same quality gates OutreachAgent applies to its own
API-generated drafts (_check_draft_integrity, is_step_1_url_violation) —
previously the Claude Code write path bypassed both, so a workflow-
generated draft's quality depended on which generator produced it. A
draft that fails either check is still inserted (so it is visible and
auditable, not silently dropped), but as approval_status='rejected' with
a rejection_reason, matching OutreachAgent's own auto-reject convention.
"""

from __future__ import annotations

import json
import sys

from backend.app.core.database import Database
from backend.app.core.config import get_settings
from backend.app.agents.outreach import _check_draft_integrity
from backend.app.core.draft_quality import is_step_1_url_violation

DRAFT_MODEL_PROVENANCE = "opus-via-claude-code"


def _build_row(d: dict, workspace_id: str) -> dict:
    return {
        "company_id": d["company_id"],
        "contact_id": d["contact_id"],
        "sequence_step": int(d["sequence_step"]),
        "subject": d["subject"],
        "body": d["body"],
        "personalization_notes": d.get("personalization_notes", ""),
        "approval_status": "pending",
        "sequence_name": d.get("sequence_name", "email_value_first"),
        "channel": d.get("channel", "email"),
        "workspace_id": workspace_id,
        "model": DRAFT_MODEL_PROVENANCE,
    }


def main(path: str) -> None:
    drafts = json.load(open(path))
    db = Database(workspace_id=get_settings().default_workspace_id)

    inserted = 0
    rejected = 0
    failed = 0
    draft_ids: list[str] = []

    for d in drafts:
        row = _build_row(d, db.workspace_id)

        violations = _check_draft_integrity(
            row["body"],
            row["subject"],
            personalization_notes=row["personalization_notes"],
            sequence_step=row["sequence_step"],
        )
        if is_step_1_url_violation(row):
            violations = [*violations, "step1_url_violation"]

        if violations:
            row["approval_status"] = "rejected"
            row["rejection_reason"] = "auto_rejected|" + " | ".join(violations[:4])

        try:
            result = db.insert_outreach_draft(row)
            if result:
                if row["approval_status"] == "rejected":
                    rejected += 1
                else:
                    inserted += 1
                if result.get("id"):
                    draft_ids.append(result["id"])
        except Exception as e:
            failed += 1
            print(
                f"INSERT_FAIL contact={d.get('contact_id')} step={d.get('sequence_step')}: {str(e)[:120]}",
                file=sys.stderr,
            )

    print(
        json.dumps(
            {
                "written": inserted,
                "rejected": rejected,
                "failed": failed,
                "draft_ids": draft_ids,
            }
        )
    )


if __name__ == "__main__":
    main(sys.argv[1])
